[package]
name = "shamirsecretsharing-cli"
version = "0.1.0"
authors = ["Daan Sprenkels <hello@dsprenkels.com>"]

[[bin]]
name = "secret-share-split"
path = "src/bin/split.rs"

[[bin]]
name = "secret-share-combine"
path = "src/bin/combine.rs"

[dependencies]
getopts = "0.2"
libc = "0.2"
rand = "0.3"
shamirsecretsharing = "0.1"
